// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://auzolgxjmkyyrhsitetr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1em9sZ3hqbWt5eXJoc2l0ZXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTI1NDksImV4cCI6MjA3MjQ2ODU0OX0.Z9f4X_NSu8ZJNAALLnwOv116q8BeNI1CKGanSHgdoUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
